openapi: 3.0.0
info:
    title: Booking
    description: Booking apis
    version: 1.0.0
paths:
    /booking:
        get:
            summary: get the latest bookings
            tags:
                - Booking
            parameters:
                - name: limit
                  in: query
                  schema:
                      type: integer
                - name: offset
                  in: query
                  schema:
                      type: integer
            responses:
                200:
                    description: OK
    /booking/status:
        get:
            summary: returns booking status
            tags:
                - Booking
            parameters:
                - name: mobileNumber
                  in: query
                  required: true
                  schema:
                      type: string
                      format: 'phone'
                - name: eventId
                  required: true
                  in: query
                  schema:
                      type: integer
                - name: startOfDayDate
                  in: query
                  required: true
                  schema:
                      type: string
                      format: 'date-time'
            responses:
                200:
                    description: OK
    /booking/authorize:
        patch:
            summary: authorizes a booking
            tags:
                - Booking
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                mobileNumber:
                                    required: true
                                    type: string
                                    format: 'phone'
                                eventId:
                                    type: integer
                                    required: true
                                startOfDayDate:
                                    required: true
                                    type: string
                                    format: 'date-time'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    msg:
                                        type: string
                                        example: UPDATED
                                    data:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                            authorized:
                                                type: boolean
